### ISSUE TITLE
Meepo's clones can buyback individually.

### ISSUE THREAD

**Issue by Ilyasnow** [furiouspuppy/Dota2_Bots#1]
[On this screenshot](http://images.akamai.steamusercontent.com/ugc/177162877534410066/21F2F00C754DDAC3F222CBE7C3AEBCE1F43E4EE6/) you can see, that Meepo's clone is alive because he bought back, but main Meepo and other clones are still dead.
It used money of real meepo to buyback. Didn't catch if he put buyback cooldown on main Meepo.

**Comment by furiouspuppy** [comment]
I've seen this before as well, wasn't sure whether or not it used meepo prime's money so I'm glad to have that confirmed.  As of now, it is default bot code and the fact that each clone gets a copy of their own causing this.  I have no control until buyback decisions are overwritten.  Will put on todo list!

Edit: Nevermind, I think I came up with an ugly hack to stop this behavior.  Let me know if you still experience it with this in place. 

added following to the end of ability_item_usage_meepo.lua:
-- attempt to disable buybacks for clones to prevent a clone buying in alone
if DotaTime() < 0 then
	--print("I would still like buy in permission plz")
	return
end

function  BuybackUsageThink()
	--print("Clones shouldn't cheat")
end

This should in theory prevent BuybackUsageThink() from being defined on meepo prime but define an empty think for clones.
