### ISSUE TITLE
Bots not spending gold

### ISSUE THREAD

**Issue by Lgk2** [furiouspuppy/Dota2_Bots#10]
Dragon knight had 10k gold and very basic items 58 minutes into the game. Bounty hunter had 3.7k gold and slightly better items.So in conclusion there seems to be some issue for certain heroes that hinders them from buying items which leaves them way weaker than they should have been.

![excessive gold](https://cloud.githubusercontent.com/assets/7945495/22175565/59ce05cc-dff7-11e6-9949-6e57cdef2f84.png)

**Comment by furiouspuppy** [comment]
This is all just default code. I'll leave it open for anyone to handle it for now.

**Comment by furiouspuppy** [comment]
I redid the builds for all 39 default bots to use my item build code.  This one should be fixed!
