### ISSUE TITLE
Meepo & Puck bot builds not working always.

### ISSUE THREAD

**Issue by TheMeGaMaN** [furiouspuppy/Dota2_Bots#11]
I have seen the Meepo & Puck bot item build bugging in almost every game.
They start buying the same item over and over again after a while. Be it multiple boots, gloves, null talisman recipes or belt of strengths. Only once have i seen Meepo actually finish a dragon lance.

I've run the lobby as local host & its been 5v5 all bots, though same happens if i'm in the game as well.
Doesn't matter which lane they take or which side they are.

**Comment by furiouspuppy** [comment]
The only way I can reproduce this is to use bot_script_reload console commands.  Whatever item is on the courier at the time will get rebuilt.  Is this with the latest workshop version?

**Comment by TheMeGaMaN** [comment]
Right now your bots crash at the VS screen, but before that i had made sure to resubscribe when ever i saw it happen. Didn't make a difference.
Do you play the bot through workshop or manually? Workshop could be the issue for me.

**Comment by furiouspuppy** [comment]
I always play my dev bots vs my workshop bots when developing and testing.  I don't have issues with the workshop bots crashing.  I will take some time this afternoon to thoroughly play through all combinations I can think of.  I have a new workshop push to make tonight so I will need to do this testing anyway.

**Comment by furiouspuppy** [comment]
@TheMeGaMaN  if you get a chance to test this push on the workshop let me know if you get any issues and/or any console errors.  I did find some strange things happening in my team_status and enemy_status files so I redid that area.  Don't know how that could break bot builds though

**Comment by TheMeGaMaN** [comment]
Your bots still crash at the VS screen. When i subscribe it doesn't seem to download anything as the download bar goes very fast.
Is there a way to make sure your bot AI is completely deleted from my PC so i can make sure workshop updates everything?

EDIT: Verified my DotA 2 files, still happening.

EDIT 2: When i open the console in the beginning of the game i can see some errors about "failed to load script..." but the game crashes very fast so cant read it.

**Comment by TheMeGaMaN** [comment]
Ok some news:
I did the manual installation and your script now works (no crash @ VS screen).
My Dota 2 folder isn't in the default C: drive so that might have something to do with it.

I will be running your bots and see if i encounter the old errors.
