### ISSUE TITLE
Skins etc.

### ISSUE THREAD

**Issue by maxmannan** [furiouspuppy/Dota2_Bots#12]
It seems that skins and other add-ons doesnt work with the experiment bots all of the time. 
About 1/10 times I start a lobby there are skins on the bots. Is that an easy fix or too complicated too bother?
Appreciate it. Keep up the good work!

**Comment by furiouspuppy** [comment]
I believe cosmetics are tied to one of the first slots on a team.  It seems hit or miss but if a human is playing in one of the first slots there should be cosmetics.  This is just Dota, I don't have access to the code to fix this unfortunately
