### ISSUE TITLE
Monkey kings ultimate monkeys Use spells and then run away from the circle

### ISSUE THREAD

**Issue by DimasDSF** [furiouspuppy/Dota2_Bots#18]
![image](https://cloud.githubusercontent.com/assets/10863746/22993556/79fb28a2-f3d4-11e6-845e-a7a2f63a3b16.png)

**Comment by furiouspuppy** [comment]
I don't have a monkey king implemented.  I have a file for him, but it isn't playable and he's never picked.  You were probably using bot experiment which I have no affiliation with except that the owner of those bots stuck my name on them cause he used my project as a starting point.

This monkey king glitch is something that needs to be fixed on valves end though
