### ISSUE TITLE
Bots cannot pickup an aegis

### ISSUE THREAD

**Issue by DimasDSF** [furiouspuppy/Dota2_Bots#19]
Instead they swap the cheapest item into the backpack and back from it

![image](https://cloud.githubusercontent.com/assets/10863746/22994087/88cc3824-f3d6-11e6-8ccf-bf2826b0865d.png)

![image](https://cloud.githubusercontent.com/assets/10863746/22994097/8fb90252-f3d6-11e6-9514-d55c26cd42bc.png)

**Comment by furiouspuppy** [comment]
You were probably using bot experiment which I have no affiliation with except that the owner of those bots stuck my name on them cause he used my project as a starting point.
