### ISSUE TITLE
Meepo buys way too many boots.

### ISSUE THREAD

**Issue by Lgk2** [furiouspuppy/Dota2_Bots#5]
![Boots](https://cloud.githubusercontent.com/assets/7945495/22175176/2255b9de-dff0-11e6-857c-e9d988fc3628.png)

The game ended with over 20 boots in total and the only other item he bought was poor man's shield.

![boots](https://cloud.githubusercontent.com/assets/7945495/22175489/e3fd178a-dff5-11e6-85ad-1c7c9e88d1b0.png)

**Comment by furiouspuppy** [comment]
Apparently valve did a patch yesterday that broke several bot API's.  The workshop and repo have been updated with a fix,  its reverts to using default courier code so the courier has more issues again but nothing I can do about that til they fix the courier API they added.
