### ISSUE TITLE
Small Improvement

### ISSUE THREAD

**Issue by Lgk2** [furiouspuppy/Dota2_Bots#8]
I noticed that bounty hunter had a recipe in his inventory while he had 3 items in his backpack, a priority system for inventories would be nice so that the bot always keeps the most expensive items in his inventory (excluding recipes since they do nothing).

![bounty hunter](https://cloud.githubusercontent.com/assets/7945495/22175372/9c8801c8-dff3-11e6-9788-cbc0c2dad5f0.png)

After the bots killed Roshan they ignored aegis which means aegis needs to be included in the priority system and if nobody takes it then they should deny it.

**Comment by furiouspuppy** [comment]
Bounty hunter is a strictly default bot.  This is default behavior and I will eventually override it when I get there.  As for the aegis, I had to disable aegis pickup or the bots with full inventory would just stand and stare at it the rest of the game.  Deny would probably be better but really it just needs rewritten to handle inventory. I'll leave this open for anyone to handle if they can.

**Comment by Lgk2** [comment]
Hm isn't there some way to disable the heroes that you haven't modified? That way the bot teams would be stronger and it'd be more obvious that you changed stuff.

**Comment by furiouspuppy** [comment]
I only have 1 good bot right now, 1 decent bot and 2 unfinished bots.  I need the default bots for now just to fill in a team.

**Comment by Lgk2** [comment]
Ah meepo, puck and clockwerk! I guess one of the most efficient ways to go about things is making a team of bots that have a good team composition.

**Comment by furiouspuppy** [comment]
Yes, that is part of the reason I stopped short on working on clockwerk.  I wasn't sure how he'd play with meepo and also, they are missing the code I need to finish puck and clockwerk.  Once they add it those heroes will get overhauled.

**Comment by furiouspuppy** [comment]
All bots now handle inventory much better with backpack and all and also will grab the aegis again
